version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9

    environment:
      TEST_RESULTS: /tmp/test-results

    working_directory: /go/src/github.com/naguigui/yelp-fusion
    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: "install dependencies"
          command: go get github.com/stretchr/testify/assert
      - run:
          name: "run vet"
          command: go vet ./yelp
      - run:
          name: "run unit tests"
          command: |
            go test -coverprofile=c.out ./yelp
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2
  build-workflow:
    jobs:
      - test
